### ISSUE TITLE
Not possible to Set Chrome Browser Locale via desiredCapabilities, browserOptions

### ISSUE THREAD

**Issue by wolczyk** [Hi-Fi/robotframework-seleniumlibrary-java#15]
I'm unable to pass Chrome Locale via  Desired Capabilities nor Browser Options. 
I noticed in the code that Desired capabilities for Chrome are not affected by parameters sent in Open Browser keyword call - not implemented.

I made it work by small code change (shown below) in createDesiredCapabilities method.
          
`  ChromeOptions options = new ChromeOptions(); `  
`  Map<String, Object> prefs = new HashMap<String, Object>();`  
`  prefs.put("intl.accept_languages", "de-AT");`  
`  options.setExperimentalOption("prefs", prefs);`  
`  desiredCapabilities.setCapability(ChromeOptions.CAPABILITY, options);`  

Is there any workaround or plan for change?

**Comment by Hi-Fi** [comment]
This can be implemented to next version, and probably to both Selenium2 and 3 sides.

**Comment by Hi-Fi** [comment]
Isn't this just matter of putting values? The example would e.g. be:
```
{"chromeOptions": {"intl.accept_languages": "de-AT"}}
```
or
```json
{"chromeOptions": {"prefs": {"intl.accept_languages": "de-AT"}}}
```

**Comment by wolczyk** [comment]
I've got serialized ChromeOptions in JSON in the following form
`{"args":[],"extensions":[],"prefs":{"intl.accept_languages":"de-AT"}}`

Today, BrowserManagement class contains only call
`desiredCapabilities = DesiredCapabilities.chrome();`

I think similar method to 'parseBrowserOptionsFirefox' would make it feasible to pass the options.

**Comment by Hi-Fi** [comment]
I think that I need to refactor that part a bit in general, as browser is only getting desired capabilities (or <Browser>Options in Selenium 3). So no browser specific things, just common parsing functions.

**Comment by Hi-Fi** [comment]
Fixed in
- 2.53.1.2
- 3.5.3.2

**Comment by wolczyk** [comment]
Thanks Juho, 2.53.1.2 works for me!
