### ISSUE TITLE
Upgrading from current Selenium2Library to SeleniumLibrary

### ISSUE THREAD

**Issue by pvsharma** [Hi-Fi/robotframework-seleniumlibrary-java#24]
I am trying to upgrade my project from selenium2Library to SeleniumLibrary but after updating my POM, downloading related jar files when I run my test it complains of not able to find the SeleniumLibrary.

I am not sure what has gone wrong or is there anything I have to consider or be careful before approaching or attempting this upgrade.

**Comment by Hi-Fi** [comment]
Steps needed for change are:
- Update POM file
- Change RF tests to refer SeleniumLibrary instead of Selenium2Library
- (if going to Selenium 3 versions) update browser and get related webdriver (can be made with plugin as made in library's testing).

Without java-version, pom-file and/or console output it's quite hard to say what's the problem, but with those 3 steps change should work.

**Comment by pvsharma** [comment]
I have updated my POM with version mentioned below

<properties>
		<project.build.sourceEncoding>cp1252</project.build.sourceEncoding>
		<robotframework.version>3.0.2</robotframework.version>
		<robotframework-seleniumlibrary.version>3.7.1.0</robotframework-seleniumlibrary.version>
		<selenium.java.version>3.7.1</selenium.java.version>
		<xml.apis.version>1.4.01</xml.apis.version>
		<javalib.core.version>1.2</javalib.core.version>
		<java.version>1.8</java.version>
		<maven.resources.plugin.version>2.5</maven.resources.plugin.version>
		<ojdbc6.version>11.2.0</ojdbc6.version>
		<xmlunit.version>1.5</xmlunit.version>
		<junit.version>4.12</junit.version>
		<hsqldb.version>2.3.0</hsqldb.version>
		<sikuli.api.version>1.1.0</sikuli.api.version>
		<sikuli.webdriver.version>1.0.1</sikuli.webdriver.version>
		<robotframework.maven.plugin.version>1.4.7</robotframework.maven.plugin.version>
		<maven.compiler.plugin.version>2.5.1</maven.compiler.plugin.version>
	</properties>

Also Test cases also changed to SeleniumLibrary.

I just switched to Chrome to avoid any issues with FireFox with my current setup.It did not complain about the SeleniumLibrary today but in turn complaining that my own keyword it is not able to recognize.

**

> Error in file 'C:\Git\Applications\Regression.txt': 
> Getting keyword names from library 'TestLibrary' failed: Calling dynamic method 'getKeywordNames' failed: NullPointerException

**

**Comment by pvsharma** [comment]
Hi Juho,

I have managed to upgrade to new versions, I hd missed out upgrading he verions for few other dependecies.Now it is working without any errors.

Next task will be for me to see what good can be implemented from all these latest versions.

Thanks again for help.I amclosing this ticket.
