### ISSUE TITLE
java.lang.IllegalArgumentException: Browser name must be htmlunit (but that is the browser name I passed in)

### ISSUE THREAD

**Issue by pmandayam** [Hi-Fi/robotframework-seleniumlibrary-java#36]
I am getting this error:

`java.lang.IllegalArgumentException: Browser name must be htmlunit`

However, that IS the browser name:

`Open Browser	url=https://www.google.com/	browserName=htmlunit`

Here is my system configuration:

Operating system: 64 bit Windows 10
Python interpret type: Jython 2.7.0.
Robot Framework version: 3.0.2 (I believe). We are using Robot maven plugin 1.4.7.
RED Plugin version: 0.8.3.

When I don't name the browser argument, but simply pass in the value, I still get the error:

`java.lang.IllegalArgumentException: Browser name must be htmlunit`

When I name the argument as `browser`, I get this error:

`com.github.markusbernhardt.seleniumlibrary.SeleniumLibraryFatalException: browser=htmlunit is not a supported browser.`

I have attached the stack trace using log level TRACE:
[trace.txt](https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/files/1745420/trace.txt)

**Comment by Hi-Fi** [comment]
What version of the library you're using? Seems that the error comes from Selenium's side, so might be that some version upgrade has broken htmlunit usage.

**Comment by pmandayam** [comment]
@Hi-Fi Hello,

I am using version 3.8.1.1:

		<dependency>
			<groupId>com.github.hi-fi</groupId>
			<artifactId>robotframework-seleniumlibrary</artifactId>
			<version>3.8.1.1</version>
			<scope>test</scope>
		</dependency>

That is the .jar I have in my local .m2 repository.

**Comment by pmandayam** [comment]
![jar-version](https://user-images.githubusercontent.com/13770435/36504859-dd6fafe2-171f-11e8-8be8-a01839cb1131.png)

**Comment by pmandayam** [comment]
Didn't mean to close ^

**Comment by Hi-Fi** [comment]
Fixed in 3.9.1.0, which is on the way to maven central

**Comment by pmandayam** [comment]
@Hi-Fi Thanks
