### ISSUE TITLE
Tests started to fail after upgrading to 3.12.x

### ISSUE THREAD

**Issue by php-coder** [Hi-Fi/robotframework-seleniumlibrary-java#53]
After upgrading from 2.53.1.1 to 3.12.0.1 my tests started to fail. It looks like, after submitting a form they immediately tries to locate elements on a page without waiting when a page will be loaded.

Is it some known issue? Any pointers to understand which component causing this and whether it's a bug or a feature will be appreciated.

**Comment by Hi-Fi** [comment]
I remembering correctly, that change came somehow from Selenium or webdriver side. Basically it doesn't same way "wait until page is loaded" every time, but continues immediately. But as said, that's my faint memory.

I have usually used explicit "Wait until element exists" or other wait keywords to handle those situations, and those were necessary also in Selenium 2 with JS UIs.

**Comment by php-coder** [comment]
Thank you for the response! I remember that somewhere I read that Selenium 2 is a drop-in replacement that's why I wasn't unsure.
