### ISSUE TITLE
getLibraryInstance() ?

### ISSUE THREAD

**Issue by homerlex** [Hi-Fi/robotframework-seleniumlibrary-java#54]
The Selenium2Library has a getLibraryInstance() method.  Is there any particular reason that was excluded from the SeleniumLibrary class?

**Comment by Hi-Fi** [comment]
The class was refactored quite completely, and that seemed like dead code. I think there was some discussion about that earlier, but apparently it was not seen so much needed that it would have taken back.

In a way I'm interested also of reasons why that's needed, and if for library extension, why that can't be part of library itself.

**Comment by homerlex** [comment]
@Hi-Fi - I wanted the instance in a library extension so I could have some keywords that invokes selenium methods.  For now I just copied the method from the Selenium2Library  and put it in my extension.  I was just curious if it was removed because there were problems with.

**Comment by Hi-Fi** [comment]
@homerlex: I think there were some issues with the instance getting method while the code was refactored. The instance getting was originally made by utilizing also Python in the process, so I would say it would be better to create library that extends the library by just adding new keywords without the need of instance getting. But same time it should be kept in mind are those extensions something that others might need, too, and why not to include those directly to the actual library.

Also, if there's really need for getting the instance, PR for that would be nice as you probably already have the code that utilizes the library.

**Comment by homerlex** [comment]
@Hi-Fi - Thanks for the information.  Most likely, in my case, extending the library would be the way to go.
