### ISSUE TITLE
Extending Selenium Library - Adding Keyword

### ISSUE THREAD

**Issue by homerlex** [Hi-Fi/robotframework-seleniumlibrary-java#55]
Do you have and example of how to extend SeleniumLibrary and add another keyword pattern that represents the classes that contain my new keywords?  Sorry if this is obvious, I'm a RobotFramework newbie.

**Comment by Hi-Fi** [comment]
Simplest option would be just to put those new keywords to package com.github.markusbernhardt.seleniumlibrary.keywords, and use SeleniumLibrary as a dependency. 

Or if wanting to use some own package for the keywords, basically 2 "initiator" classes needs to be copied (or rewritten); https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/blob/master/src/main/java/SeleniumLibrary.java and https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/blob/master/src/main/java/com/github/markusbernhardt/seleniumlibrary/SeleniumLibrary.java.

This is more Java than RF thing. The solutions described are also quite quick-and-dirty kind, as with first one library name stays as original one, and with second one updates might require manual update (quite unlikely, as those initiators are not probably going to be changed).

**Comment by homerlex** [comment]
Thank @Hi-Fi  - that's what I figured but wanted to make sure I wasn't missing anything.  I created some keyword classes in the com.github.markusbernhardt.seleniumlibrary.keywords for now.
