### ISSUE TITLE
How to call a method in another keyword class?

### ISSUE THREAD

**Issue by homerlex** [Hi-Fi/robotframework-seleniumlibrary-java#57]
I created a keyword class for my own keywords.  I want to call the waitUntilElementIsSuccessfullyClicked() method in Waiting for a given element.  Is this possible?

**Comment by Hi-Fi** [comment]
Javalib-core offers autowiring of classes. That should work also that case.

**Comment by homerlex** [comment]
Thanks @Hi-Fi - autowiring did the trick.
