### ISSUE TITLE
Deprecating warning messages when using lists

### ISSUE THREAD

**Issue by patrijuh** [Hi-Fi/robotframework-seleniumlibrary-java#69]
When using lists, there comes not expected deprecated warning messages.

Example:

@{list}=  Create List  Username  Password
Wait Until Page Contains  ${list[1]}

In latter kw there comes an warning:

 '=' is deprecated as locator strategy separator. ':' should be used instead

**Comment by Hi-Fi** [comment]
Fixed already with #68. Releasing fix now.

**Comment by Hi-Fi** [comment]
Currently release if blocked because of Travis's issue with access to Maven central.
