### ISSUE TITLE
Element Should (Not) Contain is case sensitive in Python but not in Java

### ISSUE THREAD

**Issue by ractoc** [Hi-Fi/robotframework-seleniumlibrary-java#75]
As of version 3.1 they made the Element Should Contain and the Element Should Not Contain case sensitive in the Python version of the SeleniumLibrary.
In de Java version, these keywords are still case insensitive.

This case sensitivity issue has been changed on multiple keywords in Python, see also:
https://github.com/robotframework/SeleniumLibrary/pull/1043

Can these keywords be brought in line with the Python version? If needed I could probably do this myself and put in a pull request.

**Comment by ractoc** [comment]
I just created a pull request which fixes this in all places related to the merge from the python library:

#76

**Comment by ractoc** [comment]
The Pull Request should be ready now. Any idea when this would be availlable in the dependency from maven central? Having it available there means I can actually use it in my build pipeline

**Comment by Hi-Fi** [comment]
I think you need it with Selenium 3 already? I planned to move to Selenium 4 with next release, but Selenium 4 itself has only Alpha release.

**Comment by ractoc** [comment]
Yeah, I currently have a testcase which needs it, so that would be with selenium 3

**Comment by Hi-Fi** [comment]
Released as 3.141.59.265, should be available soon in Maven Central.
