### ISSUE TITLE
"Table Header Should Contain" might get <th> elements from footer

### ISSUE THREAD

**Issue by php-coder** [Hi-Fi/robotframework-seleniumlibrary-java#89]
`Table Header Should Contain` keyword is looking for `<th>` elements everywhere in a table:

https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/blob/fed6f0e95b5cf5a365f8357a9976ec9ed7ff7e1e/src/main/java/com/github/markusbernhardt/seleniumlibrary/locators/TableElementFinder.java#L16

Given that `<th>` tag can be enclosed within `<tfoot>`, it doesn't seem right to treat it as a header.

**Comment by php-coder** [comment]
I've submitted this to upstream too: https://github.com/robotframework/SeleniumLibrary/issues/1437

**Comment by Hi-Fi** [comment]
This is not so straight forward, as th is header at every place, even at rows (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th).

This is also how the keyword is documented; `Verify the content of any table header cells of the table`
