### ISSUE TITLE
How we can run tests in parallel execution?

### ISSUE THREAD

**Issue by YauheniPo** [Hi-Fi/robotframework-seleniumlibrary-java#94]
is it possible to perform?

**Comment by Hi-Fi** [comment]
I have done that at the CI (Bamboo) by executing certain tags in parallel jobs, and then merging reports with rebot (at that time Python version). 

I don't know how browsers are handled if parallel run is made that the local machine.

**Comment by YauheniPo** [comment]
thanks for the information
Pabot lib will not help for it?

**Comment by Hi-Fi** [comment]
I haven't tested if pabot works with Jython, and still it might have issue with browsers itself (if not running with Grid).

**Comment by YauheniPo** [comment]
Thanks a lot
